default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: g2-rails-practice-delete-bad-data-development

test:
  <<: *default
  database: g2-rails-practice-delete-bad-data-test
